use super::linux_helper_setup::HelperFailure;

impl HelperFailure {
    pub(super) fn from_code(code: &[u8]) -> Option<Self> {
        match code {
            b"host-policy-denied" => Some(Self::HostPolicyDenied),
            b"namespace-setup" => Some(Self::NamespaceSetup),
            b"loopback-setup" => Some(Self::LoopbackSetup),
            b"network-canary" => Some(Self::NetworkCanary),
            b"descriptor-leak" => Some(Self::DescriptorLeak),
            b"privilege-drop" => Some(Self::PrivilegeDrop),
            b"socket-policy-compile" => Some(Self::SocketPolicyCompile),
            b"socket-policy-install" => Some(Self::SocketPolicyInstall),
            b"socket-policy-inactive" => Some(Self::SocketPolicyInactive),
            b"socket-policy-behavior" => Some(Self::SocketPolicyBehavior),
            b"managed-device-boundary-unavailable" => Some(Self::ManagedDeviceBoundaryUnavailable),
            b"managed-device-boundary-setup" => Some(Self::ManagedDeviceBoundarySetup),
            b"managed-private-propagation-setup" => Some(Self::ManagedPrivatePropagationSetup),
            b"managed-null-stage-mount" => Some(Self::ManagedNullStageMount),
            b"managed-device-tmpfs-setup" => Some(Self::ManagedDeviceTmpfsSetup),
            b"managed-null-staging-setup" => Some(Self::ManagedNullStagingSetup),
            b"managed-null-bind" => Some(Self::ManagedNullBind),
            b"managed-null-mount-remount" => Some(Self::ManagedNullMountRemount),
            b"managed-proc-setup" => Some(Self::ManagedProcSetup),
            b"managed-device-boundary-behavior" => Some(Self::ManagedDeviceBoundaryBehavior),
            b"managed-containment-policy-compile" => Some(Self::ManagedContainmentPolicyCompile),
            b"managed-containment-policy-install" => Some(Self::ManagedContainmentPolicyInstall),
            b"managed-containment-policy-inactive" => Some(Self::ManagedContainmentPolicyInactive),
            b"managed-containment-policy-behavior" => Some(Self::ManagedContainmentPolicyBehavior),
            b"runtime-input-object-mismatch" => Some(Self::RuntimeInputObjectMismatch),
            b"runtime-input-boundary-unavailable" => Some(Self::RuntimeInputBoundaryUnavailable),
            b"runtime-input-boundary-setup" => Some(Self::RuntimeInputBoundarySetup),
            b"runtime-input-boundary-behavior" => Some(Self::RuntimeInputBoundaryBehavior),
            b"filesystem-isolation-unavailable" => Some(Self::FilesystemIsolationUnavailable),
            b"filesystem-isolation-setup" => Some(Self::FilesystemIsolationSetup),
            b"filesystem-alias-propagation" => Some(Self::FilesystemAliasPropagation),
            b"filesystem-alias-workspace" => Some(Self::FilesystemAliasWorkspace),
            b"filesystem-alias-input" => Some(Self::FilesystemAliasInput),
            b"filesystem-alias-input-permission" => Some(Self::FilesystemAliasInputPermission),
            b"filesystem-alias-input-not-found" => Some(Self::FilesystemAliasInputNotFound),
            b"filesystem-alias-output" => Some(Self::FilesystemAliasOutput),
            b"filesystem-isolation-behavior" => Some(Self::FilesystemIsolationBehavior),
            b"controlled-build-object-mismatch" => Some(Self::ControlledBuildObjectMismatch),
            b"controlled-build-output-not-empty" => Some(Self::ControlledBuildOutputNotEmpty),
            b"controlled-build-snapshot-timeout" => Some(Self::ControlledBuildSnapshotTimeout),
            b"startup-timeout" => Some(Self::StartupTimeout),
            b"bootstrap-root-preparation" => Some(Self::BootstrapRootPreparation),
            b"bootstrap-root-verification" => Some(Self::BootstrapRootVerification),
            b"invalid-launch" => Some(Self::InvalidLaunch),
            _ => None,
        }
    }
}
