//! Immutable artifact facts, qualification evidence, and activation contracts.

#![forbid(unsafe_code)]
#![deny(missing_docs)]

mod activation;
mod artifact;
mod artifact_set;
mod effective_package;
mod evaluation;
mod generation_qualification;
mod host_environment;
mod installed_artifact_set;
mod model_package;
mod model_trust;
mod native_load;
mod package_source;
mod qualification;
mod qualification_v2;
mod runtime_identity;
mod runtime_package;

pub use activation::{
    ActivationAction, ActivationDecision, ActivationDecisionError, ActivationError, ActivationId,
    ActiveArtifactBinding, InstallationError, InstalledArtifact, QualificationInvalidation,
    QualificationInvalidationError, activate,
};
pub use artifact::{
    ARTIFACT_MANIFEST_SCHEMA_VERSION, ArtifactId, ArtifactManifest, ArtifactRole, ArtifactSource,
    DeclaredCapabilities, LicenseRecord, ManifestError, TokenizerIdentity,
};
pub use artifact_set::{
    ARTIFACT_SET_MANIFEST_SCHEMA_VERSION, ArtifactSetId, ArtifactSetManifest,
    ArtifactSetManifestError, ArtifactSetMember, ArtifactSetPathError, ArtifactSetRelativePath,
    MAX_ARTIFACT_SET_MANIFEST_JSON_BYTES, MAX_ARTIFACT_SET_MEMBERS,
    MAX_ARTIFACT_SET_PATH_COMPONENT_BYTES, MAX_ARTIFACT_SET_RELATIVE_PATH_BYTES,
    MAX_ARTIFACT_SET_TOTAL_PATH_BYTES,
};
pub use effective_package::{
    EFFECTIVE_PACKAGE_EVIDENCE_SCHEMA_VERSION, EFFECTIVE_PACKAGE_EVIDENCE_V2_SCHEMA_VERSION,
    EffectivePackageEvidence, EffectivePackageEvidenceError, EffectivePackageEvidenceId,
    EffectivePackageEvidenceInput, EffectivePackageEvidenceMode, EffectivePackageEvidenceRoleV2,
    EffectivePackageEvidenceV2, EffectivePackageEvidenceV2Error, EffectivePackageEvidenceV2Id,
    EffectivePackageEvidenceV2Input, EffectivePackageMemberEvidence,
    EffectivePackageMemberEvidenceV2, EffectivePackageMemberPurpose, EffectivePackageMemberUseV2,
    MAX_EFFECTIVE_PACKAGE_CANONICAL_BYTES, MAX_EFFECTIVE_PACKAGE_EVIDENCE_JSON_BYTES,
    MAX_EFFECTIVE_PACKAGE_EVIDENCE_V2_CANONICAL_BYTES,
    MAX_EFFECTIVE_PACKAGE_EVIDENCE_V2_JSON_BYTES, MAX_EFFECTIVE_PACKAGE_MEMBER_PURPOSES,
    MAX_EFFECTIVE_PACKAGE_MEMBER_V2_ASSIGNMENTS, MAX_EFFECTIVE_PACKAGE_MEMBER_V2_PURPOSES,
    MAX_EFFECTIVE_PACKAGE_MEMBER_V2_ROLES, MAX_EFFECTIVE_PACKAGE_PURPOSE_ASSIGNMENTS,
    PackageTransformationDisposition,
};
pub use evaluation::{EvaluationCase, ExpectedOutput, ReferenceJudgment};
pub use generation_qualification::{
    CANDIDATE_CONTENT_DIGEST_DOMAIN, CANDIDATE_DETERMINISTIC_EVALUATION_ID_DOMAIN,
    CANDIDATE_DETERMINISTIC_POLICY_DOMAIN, CANDIDATE_DETERMINISTIC_REPORT_DIGEST_DOMAIN,
    CANDIDATE_DETERMINISTIC_REPORT_PAIR_DIGEST_DOMAIN,
    CANDIDATE_DETERMINISTIC_SUITE_PAIR_DIGEST_DOMAIN, CANDIDATE_EVIDENCE_ID_DOMAIN,
    CANDIDATE_GENERATION_ATTEMPT_PRECURSOR_ID_DOMAIN,
    CANDIDATE_GENERATION_ATTEMPT_RECORD_ID_DOMAIN, CANDIDATE_GENERATION_CLEANUP_ID_DOMAIN,
    CANDIDATE_GENERATION_EVIDENCE_BUNDLE_ID_DOMAIN,
    CANDIDATE_GENERATION_EVIDENCE_READBACK_ID_DOMAIN, CANDIDATE_GENERATION_RECEIPT_ID_DOMAIN,
    CANDIDATE_GENERATION_RECEIPT_SET_ID_DOMAIN, CANDIDATE_JUDGE_ATTEMPT_SEED_DOMAIN,
    CANDIDATE_JUDGE_JOIN_ID_DOMAIN, CANDIDATE_JUDGE_OBSERVATION_BATCH_ID_DOMAIN,
    CANDIDATE_JUDGE_OBSERVATION_ID_DOMAIN, CANDIDATE_JUDGE_PLAN_ID_DOMAIN,
    CANDIDATE_JUDGE_PRESENTATION_ORDER_DOMAIN, CANDIDATE_JUDGE_REQUEST_AGGREGATE_ID_DOMAIN,
    CANDIDATE_JUDGE_RESPONSE_AGGREGATE_ID_DOMAIN, CANDIDATE_JUDGE_RESPONSE_ID_DOMAIN,
    CANDIDATE_JUDGE_SCHEDULE_ID_DOMAIN, CANDIDATE_JUDGE_SCHEMA_VERSION,
    CANDIDATE_JUDGE_TRIAGE_REPORT_DOMAIN, CANDIDATE_RECEIPT_PAIR_SET_ID_DOMAIN,
    CANDIDATE_SELECTION_POLICY_ID_DOMAIN, CandidateArtifactEntryV1,
    CandidateDeterministicEvaluationId, CandidateDeterministicEvaluationRecordV1,
    CandidateDeterministicEvaluationRecordV1Input, CandidateDeterministicEvaluationStatusV1,
    CandidateDeterministicReportRelationshipV1, CandidateDeterministicReportSummaryV1,
    CandidateDeterministicTransformationCoverageV1, CandidateEvidenceId,
    CandidateGenerationAttemptCleanupDispositionV1, CandidateGenerationAttemptDispositionV1,
    CandidateGenerationAttemptFailureCategoryV1, CandidateGenerationAttemptFailurePhaseV1,
    CandidateGenerationAttemptFailureV1Input, CandidateGenerationAttemptOutcomeV1,
    CandidateGenerationAttemptPrecursorId, CandidateGenerationAttemptPrecursorV1,
    CandidateGenerationAttemptPrecursorV1Input, CandidateGenerationAttemptRecordId,
    CandidateGenerationAttemptRecordV1, CandidateGenerationAttemptRecordV1Preflight,
    CandidateGenerationCleanupFailureCategoryV1, CandidateGenerationCleanupId,
    CandidateGenerationCleanupRecordV1, CandidateGenerationCleanupRecordV1Input,
    CandidateGenerationEvidenceBundleEntryV1, CandidateGenerationEvidenceBundleId,
    CandidateGenerationEvidenceBundleManifestV1,
    CandidateGenerationEvidenceBundleManifestV1Preflight,
    CandidateGenerationEvidenceBundleManifestV1Relations,
    CandidateGenerationEvidenceBundlePublicationModeV1,
    CandidateGenerationEvidenceBundleReadbackId, CandidateGenerationEvidenceBundleReadbackStatusV1,
    CandidateGenerationEvidenceBundleReadbackV1, CandidateGenerationEvidenceBundleRoleV1,
    CandidateGenerationPackageRevalidationStatusV1, CandidateGenerationProcessCleanupStatusV1,
    CandidateGenerationReceiptEvidenceClassV1, CandidateGenerationReceiptId,
    CandidateGenerationReceiptSetEntryV1, CandidateGenerationReceiptSetId,
    CandidateGenerationReceiptSetV1, CandidateGenerationReceiptSetV1Relations,
    CandidateGenerationReceiptV1, CandidateGenerationReceiptV1Preflight,
    CandidateGenerationReceiptV1Relations, CandidateGenerationUsageObservationV1,
    CandidateJudgeCaseV1, CandidateJudgeChoiceV1, CandidateJudgeEvidenceClassV1,
    CandidateJudgeJoinId, CandidateJudgeJoinRecordV1, CandidateJudgeJoinRecordV1Relations,
    CandidateJudgeLimitsV1, CandidateJudgeObservationBatchId, CandidateJudgeObservationBatchV1,
    CandidateJudgeObservationId, CandidateJudgeObservationV1, CandidateJudgeOrderPolicyV1,
    CandidateJudgePlanId, CandidateJudgePlanV1, CandidateJudgePlanV1Input,
    CandidateJudgePlanV1Relations, CandidateJudgePresentationV1, CandidateJudgeRequestAggregateId,
    CandidateJudgeRequestAggregateV1, CandidateJudgeResponseAggregateId,
    CandidateJudgeResponseAggregateV1, CandidateJudgeResponseId, CandidateJudgeResponseV1,
    CandidateJudgeScheduleEntryV1, CandidateJudgeScheduleId, CandidateJudgeScheduleV1,
    CandidateJudgeTriageReportRelationshipV1, CandidateOutputCeilingsV1, CandidateReceiptPairSetId,
    CandidateSelectionPolicyEntryV1, CandidateSelectionPolicyId, CandidateSelectionPolicyV1,
    EVIDENCE_BUNDLE_MANIFEST_RELATIVE_PATH, FrozenExternalComponentSetId,
    GENERATION_ATTEMPT_LEDGER_MANIFEST_ID_DOMAIN, GENERATION_ATTEMPT_LEDGER_ROOT_DOMAIN,
    GENERATION_CASE_FORMAT_DIGEST_DOMAIN, GENERATION_CASE_ID_DOMAIN,
    GENERATION_CASE_LANGUAGE_DIGEST_DOMAIN, GENERATION_CASE_REQUEST_PROFILE_SCHEMA_VERSION,
    GENERATION_CASE_REWRITE_MODE_DIGEST_DOMAIN, GENERATION_CLUSTER_ID_DOMAIN,
    GENERATION_DETERMINISTIC_CASE_CONTRACT_SCHEMA_VERSION,
    GENERATION_HUMAN_ADJUDICATION_EVIDENCE_MANIFEST_ID_DOMAIN,
    GENERATION_HUMAN_ADJUDICATION_EVIDENCE_ROOT_DOMAIN,
    GENERATION_HUMAN_ADJUDICATION_POLICY_DENIAL_RECORD_ID_DOMAIN,
    GENERATION_QUALIFICATION_PLAN_ID_DOMAIN, GENERATION_REPEATABILITY_EVIDENCE_MANIFEST_ID_DOMAIN,
    GENERATION_REPEATABILITY_EVIDENCE_ROOT_DOMAIN, GENERATION_REPEATABILITY_RESULT_ID_DOMAIN,
    GENERATION_REPETITION_ID_DOMAIN, GENERATION_RESOURCE_ATTEMPT_RESULT_ID_DOMAIN,
    GENERATION_RESOURCE_EVIDENCE_MANIFEST_ID_DOMAIN, GENERATION_RESOURCE_EVIDENCE_ROOT_DOMAIN,
    GENERATION_RESOURCE_POLICY_DENIAL_RECORD_ID_DOMAIN, GENERATION_SUITE_MANIFEST_ID_DOMAIN,
    GENERATION_SYSTEM_ID_DOMAIN, GenerationAttemptLedgerManifestId,
    GenerationAttemptLedgerManifestV1, GenerationAttemptLedgerManifestV1Relations,
    GenerationCaseAtomicityV1, GenerationCaseFormatV1, GenerationCaseId, GenerationCaseLanguageV1,
    GenerationCaseManifestV1, GenerationCaseManifestV1Input, GenerationCaseProtectionPolicyV1,
    GenerationCaseRequestProfileError, GenerationCaseRequestProfileV1, GenerationCaseStylePolicyV1,
    GenerationCaseUnitPolicyV1, GenerationClusterId, GenerationClusterRecordV1,
    GenerationDeterministicCaseContractError, GenerationDeterministicCaseContractV1,
    GenerationDeterministicCaseContractV1Input, GenerationHumanAdjudicationEvidenceManifestId,
    GenerationHumanAdjudicationEvidenceManifestV1,
    GenerationHumanAdjudicationEvidenceManifestV1Relations,
    GenerationHumanAdjudicationPolicyDenialRecordId,
    GenerationHumanAdjudicationPolicyDenialRecordV1,
    GenerationHumanAdjudicationPolicyDenialRecordV1Relations, GenerationPhasePolicyDenialReasonV1,
    GenerationQualificationContractError, GenerationQualificationPhaseEvidenceError,
    GenerationQualificationPhaseScopeV1, GenerationQualificationPhaseStatusV1,
    GenerationQualificationPlanId, GenerationQualificationPlanLimitsV1,
    GenerationQualificationPlanV1, GenerationQualificationPlanV1Input,
    GenerationQualificationRetryPolicyV1, GenerationRepeatabilityEvidenceManifestId,
    GenerationRepeatabilityEvidenceManifestV1, GenerationRepeatabilityEvidenceManifestV1Relations,
    GenerationRepeatabilityResultId, GenerationRepeatabilityResultRecordV1,
    GenerationRepeatabilityResultRecordV1Relations, GenerationRepeatabilityTerminalStageV1,
    GenerationRepetitionId, GenerationRepetitionRecordV1, GenerationRequestBindingId,
    GenerationResourceAttemptResultId, GenerationResourceAttemptResultRecordV1,
    GenerationResourceAttemptResultRecordV1Input, GenerationResourceAttemptResultRecordV1Relations,
    GenerationResourceEvidenceManifestId, GenerationResourceEvidenceManifestV1,
    GenerationResourceEvidenceManifestV1Relations, GenerationResourceExceededLimitV1,
    GenerationResourceObservationProfileV1, GenerationResourcePolicyDenialRecordId,
    GenerationResourcePolicyDenialRecordV1, GenerationResourcePolicyDenialRecordV1Relations,
    GenerationSuiteManifestId, GenerationSuiteManifestV1, GenerationSystemId,
    GenerationSystemRecordV1, GenerationSystemRecordV1Input, GenerationSystemRecordV1Relations,
    MANAGED_LOCAL_JUDGE_CONNECTION_OBSERVATION_AGGREGATE_DOMAIN,
    MANAGED_LOCAL_JUDGE_EFFECTIVE_RUNTIME_STATE_JOIN_DOMAIN,
    MANAGED_LOCAL_JUDGE_EFFECTIVE_STATE_OBSERVATION_AGGREGATE_DOMAIN,
    MANAGED_LOCAL_JUDGE_NATIVE_LOAD_OBSERVATION_AGGREGATE_DOMAIN,
    MANAGED_LOCAL_JUDGE_PROCESS_OBSERVATION_AGGREGATE_DOMAIN,
    MANAGED_LOCAL_JUDGE_RECEIPT_ID_DOMAIN, MANAGED_LOCAL_JUDGE_RESIDENCY_AGGREGATE_DOMAIN,
    MANAGED_OLLAMA_CANDIDATE_EVIDENCE_ID_DOMAIN,
    MANAGED_OLLAMA_CANDIDATE_GENERATION_EVIDENCE_SCHEMA_VERSION,
    MAX_CANDIDATE_DETERMINISTIC_EVALUATION_JSON_BYTES,
    MAX_CANDIDATE_DETERMINISTIC_REPORT_JSON_BYTES,
    MAX_CANDIDATE_GENERATION_ATTEMPT_PRECURSOR_JSON_BYTES,
    MAX_CANDIDATE_GENERATION_ATTEMPT_RECORD_JSON_BYTES,
    MAX_CANDIDATE_GENERATION_CLEANUP_JSON_BYTES,
    MAX_CANDIDATE_GENERATION_EVIDENCE_BUNDLE_JSON_BYTES,
    MAX_CANDIDATE_GENERATION_EVIDENCE_BUNDLE_READBACK_JSON_BYTES,
    MAX_CANDIDATE_GENERATION_RECEIPT_JSON_BYTES, MAX_CANDIDATE_GENERATION_RECEIPT_SET_JSON_BYTES,
    MAX_CANDIDATE_JUDGE_JOIN_JSON_BYTES, MAX_CANDIDATE_JUDGE_OBSERVATION_BATCH_JSON_BYTES,
    MAX_CANDIDATE_JUDGE_PLAN_JSON_BYTES, MAX_CANDIDATE_JUDGE_REQUEST_AGGREGATE_JSON_BYTES,
    MAX_CANDIDATE_JUDGE_RESPONSE_AGGREGATE_JSON_BYTES, MAX_CANDIDATE_JUDGE_SCHEDULE_JSON_BYTES,
    MAX_CANDIDATE_JUDGE_TRIAGE_REPORT_JSON_BYTES, MAX_CANDIDATE_SELECTION_POLICY_JSON_BYTES,
    MAX_GENERATION_CANDIDATES_PER_COMPLETION, MAX_GENERATION_CASE_JSON_BYTES,
    MAX_GENERATION_CASE_REQUEST_PROFILE_JSON_BYTES, MAX_GENERATION_CLUSTER_JSON_BYTES,
    MAX_GENERATION_DETERMINISTIC_CASE_CONTRACT_JSON_BYTES,
    MAX_GENERATION_DETERMINISTIC_CASE_PROTECTED_TERMS,
    MAX_GENERATION_DETERMINISTIC_CASE_RUBRIC_CLAUSES, MAX_GENERATION_EVIDENCE_BUNDLE_BYTES,
    MAX_GENERATION_EVIDENCE_BUNDLE_ENTRIES, MAX_GENERATION_EVIDENCE_RELATIVE_PATH_BYTES,
    MAX_GENERATION_MACHINE_KEY_BYTES, MAX_GENERATION_PHASE_POLICY_DENIAL_RECORD_JSON_BYTES,
    MAX_GENERATION_PLAN_JSON_BYTES, MAX_GENERATION_QUALIFICATION_PHASE_ITEMS,
    MAX_GENERATION_QUALIFICATION_PHASE_MANIFEST_JSON_BYTES,
    MAX_GENERATION_REPEATABILITY_RESULT_JSON_BYTES, MAX_GENERATION_REPETITION_JSON_BYTES,
    MAX_GENERATION_RESOURCE_ATTEMPT_RESULT_JSON_BYTES, MAX_GENERATION_RETAINED_INPUT_BYTES,
    MAX_GENERATION_SUITE_CASES, MAX_GENERATION_SUITE_JSON_BYTES, MAX_GENERATION_SYSTEM_JSON_BYTES,
    MAX_GENERATION_SYSTEMS_PER_PLAN, MAX_MANAGED_LOCAL_JUDGE_RECEIPT_JSON_BYTES,
    MAX_MANAGED_OLLAMA_CANDIDATE_GENERATION_EVIDENCE_V2_JSON_BYTES,
    MAX_PLANNED_CANDIDATE_ATTEMPT_JSON_BYTES, MAX_PLANNED_GENERATION_ATTEMPTS,
    ManagedGenerationPathId, ManagedLocalJudgeEvidenceClassV1, ManagedLocalJudgeReceiptId,
    ManagedLocalJudgeReceiptRecordV1, ManagedLocalJudgeReceiptRecordV1Input,
    ManagedLocalJudgeReceiptRecordV1Relations, ManagedLocalJudgeReceiptSuccessStatusV1,
    ManagedOllamaCandidateGenerationEvidenceClassV2, ManagedOllamaCandidateGenerationEvidenceV2,
    ManagedOllamaCandidateGenerationEvidenceV2Id, ManagedOllamaCandidateGenerationEvidenceV2Input,
    ManagedOllamaCandidateGenerationEvidenceV2Relations, ManagedOllamaEffectiveRuntimeStateJoinId,
    ManagedOllamaGenerationBracketObservationV1Id, OllamaRetainedSessionResponseId,
    PLANNED_CANDIDATE_ATTEMPT_ID_DOMAIN, PlannedCandidateAttemptId, PlannedCandidateAttemptV1,
    PlannedCandidateAttemptV1Input, PlannedCandidateAttemptV1Relations, RuntimeAdmissionJoinId,
    StructuredCompletionRequestBindingId, StructuredResponseArtifactV1Input,
    candidate_deterministic_policy_digest,
};
pub use generation_qualification::{
    GENERATION_QUALIFICATION_INVALIDATION_ID_DOMAIN, GENERATION_QUALIFICATION_RECORD_ID_DOMAIN,
    GENERATION_QUALIFICATION_SELECTION_ID_DOMAIN, GenerationQualificationId,
    GenerationQualificationInvalidationId, GenerationQualificationInvalidationV1,
    GenerationQualificationInvalidationV1Error, GenerationQualificationInvalidationV1Relations,
    GenerationQualificationRecordV1, GenerationQualificationRecordV1Error,
    GenerationQualificationRecordV1Relations, GenerationQualificationSelectionId,
    GenerationQualificationSelectionV1, GenerationQualificationSelectionV1Error,
    GenerationQualificationSelectionV1Relations, GenerationQualificationStatusV1,
    MAX_GENERATION_QUALIFICATION_INVALIDATION_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_INVALIDATION_JSON_BYTES,
    MAX_GENERATION_QUALIFICATION_RECORD_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_RECORD_JSON_BYTES,
    MAX_GENERATION_QUALIFICATION_SELECTION_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_SELECTION_JSON_BYTES,
};
pub use generation_qualification::{
    GENERATION_QUALIFICATION_LICENSE_ASSESSMENT_POLICY_ID_DOMAIN,
    GENERATION_QUALIFICATION_LICENSE_EVIDENCE_ID_DOMAIN,
    GENERATION_QUALIFICATION_OPERATION_CANDIDATES_PER_COMPLETION,
    GENERATION_QUALIFICATION_OPERATION_CONCURRENT_ATTEMPTS,
    GENERATION_QUALIFICATION_OPERATION_POLICY_ID_DOMAIN,
    GENERATION_QUALIFICATION_OPERATION_RECEIPT_ID_DOMAIN,
    GENERATION_QUALIFICATION_PHASE_INTERRUPTION_RECORD_ID_DOMAIN,
    GENERATION_QUALIFICATION_PLAN_FAILURE_POLICY_DOMAIN,
    GENERATION_QUALIFICATION_PLATFORM_ASSESSMENT_POLICY_ID_DOMAIN,
    GENERATION_QUALIFICATION_PLATFORM_EVIDENCE_ID_DOMAIN,
    GENERATION_QUALIFICATION_REQUEST_PROJECTION_ID_DOMAIN, GenerationQualificationDecisionRuleV1,
    GenerationQualificationInterruptedPhaseV1, GenerationQualificationLicenseAssessmentPolicyId,
    GenerationQualificationLicenseDecisionV1, GenerationQualificationLicenseEvidenceId,
    GenerationQualificationLicenseEvidenceV1, GenerationQualificationLicenseEvidenceV1Input,
    GenerationQualificationLicenseEvidenceV1Relations, GenerationQualificationLicensePermissionV1,
    GenerationQualificationLicenseReasonV1, GenerationQualificationOperationContractError,
    GenerationQualificationOperationFinalizationStatusV1, GenerationQualificationOperationLimitsV1,
    GenerationQualificationOperationPolicyId, GenerationQualificationOperationPolicyV1,
    GenerationQualificationOperationPolicyV1Input,
    GenerationQualificationOperationPolicyV1Relations, GenerationQualificationOperationReceiptId,
    GenerationQualificationOperationReceiptV1, GenerationQualificationOperationReceiptV1Input,
    GenerationQualificationOperationReceiptV1Relations,
    GenerationQualificationOperationSystemRelationsV1,
    GenerationQualificationOperationTerminalStatusV1, GenerationQualificationPhaseCheckpointV1,
    GenerationQualificationPhaseInterruptionReasonV1,
    GenerationQualificationPhaseInterruptionRecordId,
    GenerationQualificationPhaseInterruptionRecordV1,
    GenerationQualificationPhaseInterruptionRecordV1Input,
    GenerationQualificationPhaseInterruptionRecordV1Relations,
    GenerationQualificationPlatformAssessmentPolicyId, GenerationQualificationPlatformEvidenceId,
    GenerationQualificationPlatformEvidenceV1, GenerationQualificationPlatformEvidenceV1Input,
    GenerationQualificationPlatformEvidenceV1Relations, GenerationQualificationPlatformReasonV1,
    GenerationQualificationPlatformStatusV1, GenerationQualificationRequestProjectionEntryV1,
    GenerationQualificationRequestProjectionEntryV1Input,
    GenerationQualificationRequestProjectionId, GenerationQualificationRequestProjectionV1,
    GenerationQualificationRequestProjectionV1Relations,
    GenerationQualificationTerminalInterruptionPlan, GenerationQualificationTerminalSetPlan,
    MAX_GENERATION_QUALIFICATION_LICENSE_EVIDENCE_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_LICENSE_EVIDENCE_JSON_BYTES,
    MAX_GENERATION_QUALIFICATION_OPERATION_CONTEXT_TOKENS,
    MAX_GENERATION_QUALIFICATION_OPERATION_INPUT_BYTES,
    MAX_GENERATION_QUALIFICATION_OPERATION_OUTPUT_BYTES,
    MAX_GENERATION_QUALIFICATION_OPERATION_OUTPUT_TOKENS,
    MAX_GENERATION_QUALIFICATION_OPERATION_POLICY_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_OPERATION_POLICY_JSON_BYTES,
    MAX_GENERATION_QUALIFICATION_OPERATION_RECEIPT_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_OPERATION_RECEIPT_JSON_BYTES,
    MAX_GENERATION_QUALIFICATION_PHASE_INTERRUPTION_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_PHASE_INTERRUPTION_JSON_BYTES,
    MAX_GENERATION_QUALIFICATION_PLATFORM_EVIDENCE_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_PLATFORM_EVIDENCE_JSON_BYTES,
    MAX_GENERATION_QUALIFICATION_POLICY_BYTES,
    MAX_GENERATION_QUALIFICATION_REQUEST_PROJECTION_CANONICAL_BYTES,
    MAX_GENERATION_QUALIFICATION_REQUEST_PROJECTION_JSON_BYTES,
    PlannedGenerationQualificationTerminalSet, generation_qualification_plan_failure_policy_digest,
};
pub use host_environment::{
    HOST_ENVIRONMENT_ARCHITECTURE_DIGEST_DOMAIN, HOST_ENVIRONMENT_EXECUTION_CLASS_DIGEST_DOMAIN,
    HOST_ENVIRONMENT_HARDWARE_ENVELOPE_DIGEST_DOMAIN, HOST_ENVIRONMENT_ID_DOMAIN,
    HOST_ENVIRONMENT_OPERATING_SYSTEM_DIGEST_DOMAIN, HOST_ENVIRONMENT_SCHEMA_VERSION,
    HostAcceleratorScopeV1, HostArchitectureDigestV1, HostArchitectureV1, HostArchitectureV1Input,
    HostEnvironmentDigestSetV1, HostEnvironmentId, HostEnvironmentV1, HostEnvironmentV1Error,
    HostEnvironmentV1Input, HostExecutionClassDigestV1, HostExecutionClassV1,
    HostExecutionClassV1Input, HostExecutionProfileV1, HostHardwareEnvelopeDigestV1,
    HostHardwareEnvelopeV1, HostHardwareEnvelopeV1Input, HostOperatingSystemDigestV1,
    HostOperatingSystemV1, HostOperatingSystemV1Input, MAX_HOST_ENVIRONMENT_CANONICAL_BYTES,
    MAX_HOST_ENVIRONMENT_JSON_BYTES, MAX_HOST_ENVIRONMENT_PROJECTION_CANONICAL_BYTES,
    MAX_HOST_ENVIRONMENT_STRING_BYTES, ObserverBinaryAssertionModeV1,
};
pub use installed_artifact_set::{
    INSTALLED_ARTIFACT_SET_SCHEMA_VERSION, InstalledArtifactSet, InstalledArtifactSetError,
    MAX_INSTALLED_ARTIFACT_SET_JSON_BYTES,
};
pub use model_package::{
    EMBEDDED_MODEL_COMPONENT_LIMIT, EmbeddedModelComponent, EmbeddedModelComponentPurpose,
    MAX_MODEL_PACKAGE_MANIFEST_JSON_BYTES, MODEL_PACKAGE_MANIFEST_SCHEMA_VERSION,
    ModelPackageManifest, ModelPackageManifestError, ModelPackageManifestId, ModelPackageMember,
    ModelPackageMemberRole, ModelWeightLayout,
};
pub use model_trust::{ModelLicenseControlId, ModelPackageFoundationId};
pub use native_load::{
    MAX_NATIVE_LOAD_COMPONENTS, MAX_NATIVE_LOAD_OBSERVATION_JSON_BYTES,
    NATIVE_LOAD_OBSERVATION_SCHEMA_VERSION, NativeLoadEvidenceClass, NativeLoadObservation,
    NativeLoadObservationError, NativeLoadObservationId, NativeLoadObservationInput,
    NativeLoadOrigin, NativeLoadVisibilityScope, NativeLoadedComponent, NativeMappingClass,
};
pub use package_source::{
    MAX_PACKAGE_SOURCE_JSON_BYTES, PACKAGE_SOURCE_SCHEMA_VERSION, PackageSource,
    PackageSourceError, PackageSourceId, PackageSourceKind, PackageTransformation,
};
pub use qualification::{
    HardwareTier, LicenseDecision, QUALIFICATION_SCHEMA_VERSION, QualificationId,
    QualificationRecord, QualificationRecordError, QualificationStatus, RuntimeIdentity,
};
pub use qualification_v2::{
    MAX_QUALIFICATION_V2_CANONICAL_BYTES, MAX_QUALIFICATION_V2_JSON_BYTES,
    QUALIFICATION_V2_SCHEMA_VERSION, QualificationRecordV2, QualificationRecordV2Error,
    QualificationRecordV2Input, QualificationV2Id,
};
pub use runtime_identity::{
    ComputeBackend, EFFECTIVE_RUNTIME_STATE_SCHEMA_VERSION, EffectiveRuntimeState,
    EffectiveRuntimeStateError, EffectiveRuntimeStateFromLoadInput, EffectiveRuntimeStateId,
    EffectiveRuntimeStateInput, ExecutionPlacement, MAX_RUNTIME_IDENTITY_JSON_BYTES,
    RUNTIME_BUILD_IDENTITY_SCHEMA_VERSION, RuntimeAbi, RuntimeArchitecture, RuntimeBuildId,
    RuntimeBuildIdentity, RuntimeBuildIdentityError, RuntimeBuildIdentityInput, RuntimeBuildMode,
    RuntimeOperatingSystem, RuntimeTarget, RuntimeTargetError,
};
pub use runtime_package::{
    MAX_RUNTIME_PACKAGE_MANIFEST_JSON_BYTES, RUNTIME_PACKAGE_MANIFEST_SCHEMA_VERSION,
    RuntimePackageLoadPolicy, RuntimePackageManifest, RuntimePackageManifestError,
    RuntimePackageManifestId, RuntimePackageMember, RuntimePackageMemberRole,
};
